import logging
import json
from datetime import datetime
from backend.app.database import SessionLocal
from backend.app.models import ActionTask, TaskStateLog, ActionTaskTemplate, User, NhanSu
from backend.app.services.sla_service import SLAService

logger = logging.getLogger(__name__)

class TaskService:
    # GOVERNANCE: Strict Task Lifecycle State Machine
    ALLOWED_TRANSITIONS = {
        'Mới': ['Đã giao', 'Hủy'],
        'Đã giao': ['Đang xử lý', 'Hủy', 'Escalation'], # NEW -> ASSIGNED -> IN_PROGRESS
        'Đang xử lý': ['Hoàn thành', 'Thất bại', 'Hủy', 'Escalation'],
        'Hoàn thành': ['Đóng'], # COMPLETED -> CLOSED
        'Thất bại': ['Đóng'],
        'Escalation': ['Đã giao', 'Hủy'],
        'Hủy': [],
        'Đóng': []
    }

    @staticmethod
    def _get_governed_now():
        """
        GOVERNANCE: Centralized time control for the Task Orchestrator.
        """
        return datetime.now()

    @staticmethod
    def validate_transition(current_status, new_status):
        """
        Hardened Lifecycle Governance
        """
        allowed = TaskService.ALLOWED_TRANSITIONS.get(current_status, [])
        if new_status not in allowed:
            raise Exception(f"CRITICAL TASK GOVERNANCE FAILURE: Illegal transition from {current_status} to {new_status}")

    @staticmethod
    def create_task_from_template(db, template_id, target_id, source_event_id=None, staff_id=None, context=None):
        """
        GOVERNANCE: Create a Task from a Template with full orchestration linkage
        """
        template = db.query(ActionTaskTemplate).get(template_id)
        if not template:
            logger.error(f"Task Template not found: {template_id}")
            return None

        now = TaskService._get_governed_now()
        
        # 0. Idempotency Check
        task_identity_key = f"TPL:{template_id}|TGT:{target_id}"
        if source_event_id:
            task_identity_key += f"|EVT:{source_event_id}"
        
        # If it's a recurring event, we might append the run_id or period to the key
        if context and context.get("run_id"):
            task_identity_key += f"|RUN:{context['run_id']}"
            
        existing = db.query(ActionTask).filter(ActionTask.task_identity_key == task_identity_key).first()
        if existing:
            logger.info(f"Task already exists for identity {task_identity_key}. Skipping creation.")
            return existing

        # 1. Create the Task
        governance_snapshot = {
            "engine_version": "3.0.0-TASK-ORCHESTRATOR-HARDENED",
            "orchestrated_at": now.isoformat(),
            "template_id": template.id,
            "target_id": target_id,
            "source_event_id": source_event_id,
            "context": context if context else {},
            "resolution_strategy": template.default_resolution_strategy
        }
        
        task = ActionTask(
            target_id=target_id,
            loai_doi_tuong=template.loai_doi_tuong,
            phan_loai_giao_viec=f"Auto: {template.tieu_de}",
            staff_id=staff_id,
            template_id=template.id,
            noi_dung=template.noi_dung_mau,
            trang_thai='Mới',
            resolution_strategy=template.default_resolution_strategy,
            resolution_config_json=template.resolution_config_json,
            source_event_id=source_event_id,
            governance_snapshot_json=json.dumps(governance_snapshot),
            task_identity_key=task_identity_key,
            created_at=now
        )
        db.add(task)
        db.flush() # Get task.id

        # 2. Link SLA Tracker (Agnostic)
        policy_code = None
        if template.resolution_config_json:
            try:
                config = json.loads(template.resolution_config_json)
                policy_code = config.get("sla_policy_code")
            except: pass
        
        if policy_code:
            sla_tracker = SLAService.attach_tracker(db, 'ACTION_TASK', str(task.id), policy_code, context)
            if sla_tracker:
                task.sla_tracker_id = sla_tracker.id
                governance_snapshot["sla_tracker_id"] = sla_tracker.id
                task.governance_snapshot_json = json.dumps(governance_snapshot)

        # 3. Create Initial State Log
        state_log = TaskStateLog(
            task_id=task.id,
            previous_status=None,
            new_status='Mới',
            action_type='CREATE',
            reason="Auto-generated by Orchestrator",
            evidence_snapshot_json=json.dumps(governance_snapshot),
            timestamp=now
        )
        db.add(state_log)
        
        db.commit()
        logger.info(f"Task CREATED: {task.id} for {target_id} via Template {template_id}")
        return task

    @staticmethod
    def update_task_status(db, task_id, new_status, action_type, user_id=None, reason=None, evidence=None):
        """
        GOVERNANCE: Governed status update with audit log
        """
        task = db.query(ActionTask).get(task_id)
        if not task: return None

        old_status = task.trang_thai
        now = TaskService._get_governed_now()
        
        # Validate Governance
        TaskService.validate_transition(old_status, new_status)
        
        task.trang_thai = new_status
        if new_status == 'Hoàn thành':
            task.updated_at = now
            # If task is met, mark SLA as met
            if task.sla_tracker_id:
                SLAService.mark_met(db, 'ACTION_TASK', str(task.id))

        # Snapshot for the state change
        change_snapshot = {
            "engine_version": "3.0.0-TASK-ORCHESTRATOR-HARDENED",
            "previous_status": old_status,
            "new_status": new_status,
            "action_type": action_type,
            "changed_at": now.isoformat(),
            "evidence": evidence if evidence else {}
        }

        log = TaskStateLog(
            task_id=task.id,
            previous_status=old_status,
            new_status=new_status,
            changed_by=user_id,
            action_type=action_type,
            reason=reason,
            evidence_snapshot_json=json.dumps(change_snapshot),
            timestamp=now
        )
        db.add(log)
        db.commit()
        return task
