import logging
import json
from datetime import datetime
from backend.app.database import SessionLocal
from backend.app.models import ActionTask, TaskStateLog, ActionTaskTemplate, User, NhanSu
from backend.app.services.sla_service import SLAService

logger = logging.getLogger(__name__)

class TaskService:
    @staticmethod
    def create_task_from_template(db, template_id, target_id, source_event_id=None, staff_id=None, context=None):
        """
        GOVERNANCE: Create a Task from a Template with full orchestration linkage
        """
        template = db.query(ActionTaskTemplate).get(template_id)
        if not template:
            logger.error(f"Task Template not found: {template_id}")
            return None

        now = datetime.now()
        
        # 1. Create the Task
        task = ActionTask(
            target_id=target_id,
            loai_doi_tuong=template.loai_doi_tuong,
            phan_loai_giao_viec=f"Auto: {template.tieu_de}",
            staff_id=staff_id,
            template_id=template.id,
            noi_dung=template.noi_dung_mau,
            trang_thai='Mới',
            resolution_strategy=template.default_resolution_strategy,
            resolution_config_json=template.resolution_config_json,
            source_event_id=source_event_id,
            governance_snapshot_json=json.dumps(context) if context else None
        )
        db.add(task)
        db.flush() # Get task.id

        # 2. Link SLA Tracker (Agnostic)
        # Search for a matching policy code for this template if applicable
        # For now, we assume a naming convention or a mapping in resolution_config
        policy_code = None
        if template.resolution_config_json:
            try:
                config = json.loads(template.resolution_config_json)
                policy_code = config.get("sla_policy_code")
            except: pass
        
        if policy_code:
            sla_tracker = SLAService.attach_tracker(db, 'ACTION_TASK', str(task.id), policy_code, context)
            if sla_tracker:
                task.sla_tracker_id = sla_tracker.id

        # 3. Create Initial State Log
        state_log = TaskStateLog(
            task_id=task.id,
            previous_status=None,
            new_status='Mới',
            action_type='CREATE',
            reason="Auto-generated by Orchestrator",
            evidence_snapshot_json=json.dumps(context) if context else None
        )
        db.add(state_log)
        
        db.commit()
        logger.info(f"Task CREATED: {task.id} for {target_id} via Template {template_id}")
        return task

    @staticmethod
    def update_task_status(db, task_id, new_status, action_type, user_id=None, reason=None, evidence=None):
        """
        GOVERNANCE: Governed status update with audit log
        """
        task = db.query(ActionTask).get(task_id)
        if not task: return None

        old_status = task.trang_thai
        task.trang_thai = new_status
        if new_status == 'Hoàn thành':
            task.ngay_hoan_thanh = datetime.now()
            # If task is met, mark SLA as met
            if task.sla_tracker_id:
                SLAService.mark_met(db, 'ACTION_TASK', str(task.id))

        log = TaskStateLog(
            task_id=task.id,
            previous_status=old_status,
            new_status=new_status,
            changed_by=user_id,
            action_type=action_type,
            reason=reason,
            evidence_snapshot_json=json.dumps(evidence) if evidence else None
        )
        db.add(log)
        db.commit()
        return task
